{"uuid":"dde2a253-8e8c-4b23-9404-e97c9f51b07b","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.qaenv is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Cypress.qaenv is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at cypress/e2e/api/createMultipleUser.js (http://localhost:61902/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:13975:21)\n    at __init (http://localhost:61902/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:9:58)\n    at eval (http://localhost:61902/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:14028:3)\n    at eval (http://localhost:61902/__cypress/tests?p=cypress\\e2e\\api\\createMultipleUser.feature:14031:3)\n    at eval (<anonymous>)\n    at <unknown> (http://localhost:61902/__cypress/runner/cypress_runner.js:111981:23)\n    at tryCatcher (http://localhost:61902/__cypress/runner/cypress_runner.js:1777:23)\n    at Object.gotValue (http://localhost:61902/__cypress/runner/cypress_runner.js:6446:18)\n    at Object.gotAccum (http://localhost:61902/__cypress/runner/cypress_runner.js:6435:25)\n    at Object.tryCatcher (http://localhost:61902/__cypress/runner/cypress_runner.js:1777:23)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:61902/__cypress/runner/cypress_runner.js:3456:19)\n    at Promise._then (http://localhost:61902/__cypress/runner/cypress_runner.js:1209:17)\n    at Promise.then (http://localhost:61902/__cypress/runner/cypress_runner.js:1102:17)\n    at runScriptsFromUrls (http://localhost:61902/__cypress/runner/cypress_runner.js:111985:136)\n    at Object.runScripts (http://localhost:61902/__cypress/runner/cypress_runner.js:112026:12)\n    at $Cypress.onSpecWindow (http://localhost:61902/__cypress/runner/cypress_runner.js:41405:67)\n    at <unknown> (http://localhost:61902/__cypress/iframes/cypress%5Ce2e%5Capi%5CcreateMultipleUser.feature?browserFamily=chromium:276:22)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress.e2e.api.createMultipleUser.feature"}],"links":[],"start":1749029557248,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1749029557264}